/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsEnum,
  IsDate,
} from "class-validator";
import { DocumentCreateNestedManyWithoutApplicationsInput } from "./DocumentCreateNestedManyWithoutApplicationsInput";
import { Type } from "class-transformer";
import { EducationCreateNestedManyWithoutApplicationsInput } from "./EducationCreateNestedManyWithoutApplicationsInput";
import { InstitutionWhereUniqueInput } from "../../institution/base/InstitutionWhereUniqueInput";
import { EnumApplicationStatus } from "./EnumApplicationStatus";
import { TrainingCreateNestedManyWithoutApplicationsInput } from "./TrainingCreateNestedManyWithoutApplicationsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { WorkExperienceCreateNestedManyWithoutApplicationsInput } from "./WorkExperienceCreateNestedManyWithoutApplicationsInput";

@InputType()
class ApplicationCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  applicationNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  comments?: string | null;

  @ApiProperty({
    required: false,
    type: () => DocumentCreateNestedManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => DocumentCreateNestedManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => DocumentCreateNestedManyWithoutApplicationsInput, {
    nullable: true,
  })
  documents?: DocumentCreateNestedManyWithoutApplicationsInput;

  @ApiProperty({
    required: false,
    type: () => EducationCreateNestedManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => EducationCreateNestedManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => EducationCreateNestedManyWithoutApplicationsInput, {
    nullable: true,
  })
  educations?: EducationCreateNestedManyWithoutApplicationsInput;

  @ApiProperty({
    required: false,
    type: () => InstitutionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => InstitutionWhereUniqueInput)
  @IsOptional()
  @Field(() => InstitutionWhereUniqueInput, {
    nullable: true,
  })
  institution?: InstitutionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumApplicationStatus,
  })
  @IsEnum(EnumApplicationStatus)
  @IsOptional()
  @Field(() => EnumApplicationStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  submissionDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => TrainingCreateNestedManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => TrainingCreateNestedManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => TrainingCreateNestedManyWithoutApplicationsInput, {
    nullable: true,
  })
  trainings?: TrainingCreateNestedManyWithoutApplicationsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => WorkExperienceCreateNestedManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => WorkExperienceCreateNestedManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => WorkExperienceCreateNestedManyWithoutApplicationsInput, {
    nullable: true,
  })
  workExperiences?: WorkExperienceCreateNestedManyWithoutApplicationsInput;
}

export { ApplicationCreateInput as ApplicationCreateInput };
