/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Education } from "./Education";
import { EducationCountArgs } from "./EducationCountArgs";
import { EducationFindManyArgs } from "./EducationFindManyArgs";
import { EducationFindUniqueArgs } from "./EducationFindUniqueArgs";
import { CreateEducationArgs } from "./CreateEducationArgs";
import { UpdateEducationArgs } from "./UpdateEducationArgs";
import { DeleteEducationArgs } from "./DeleteEducationArgs";
import { Application } from "../../application/base/Application";
import { User } from "../../user/base/User";
import { EducationService } from "../education.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Education)
export class EducationResolverBase {
  constructor(
    protected readonly service: EducationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Education",
    action: "read",
    possession: "any",
  })
  async _educationsMeta(
    @graphql.Args() args: EducationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Education])
  @nestAccessControl.UseRoles({
    resource: "Education",
    action: "read",
    possession: "any",
  })
  async educations(
    @graphql.Args() args: EducationFindManyArgs
  ): Promise<Education[]> {
    return this.service.educations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Education, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Education",
    action: "read",
    possession: "own",
  })
  async education(
    @graphql.Args() args: EducationFindUniqueArgs
  ): Promise<Education | null> {
    const result = await this.service.education(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Education)
  @nestAccessControl.UseRoles({
    resource: "Education",
    action: "create",
    possession: "any",
  })
  async createEducation(
    @graphql.Args() args: CreateEducationArgs
  ): Promise<Education> {
    return await this.service.createEducation({
      ...args,
      data: {
        ...args.data,

        application: args.data.application
          ? {
              connect: args.data.application,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Education)
  @nestAccessControl.UseRoles({
    resource: "Education",
    action: "update",
    possession: "any",
  })
  async updateEducation(
    @graphql.Args() args: UpdateEducationArgs
  ): Promise<Education | null> {
    try {
      return await this.service.updateEducation({
        ...args,
        data: {
          ...args.data,

          application: args.data.application
            ? {
                connect: args.data.application,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Education)
  @nestAccessControl.UseRoles({
    resource: "Education",
    action: "delete",
    possession: "any",
  })
  async deleteEducation(
    @graphql.Args() args: DeleteEducationArgs
  ): Promise<Education | null> {
    try {
      return await this.service.deleteEducation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Application, {
    nullable: true,
    name: "application",
  })
  @nestAccessControl.UseRoles({
    resource: "Application",
    action: "read",
    possession: "any",
  })
  async getApplication(
    @graphql.Parent() parent: Education
  ): Promise<Application | null> {
    const result = await this.service.getApplication(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Education): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
