/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TrainingService } from "../training.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TrainingCreateInput } from "./TrainingCreateInput";
import { Training } from "./Training";
import { TrainingFindManyArgs } from "./TrainingFindManyArgs";
import { TrainingWhereUniqueInput } from "./TrainingWhereUniqueInput";
import { TrainingUpdateInput } from "./TrainingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TrainingControllerBase {
  constructor(
    protected readonly service: TrainingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Training })
  @nestAccessControl.UseRoles({
    resource: "Training",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTraining(
    @common.Body() data: TrainingCreateInput
  ): Promise<Training> {
    return await this.service.createTraining({
      data: {
        ...data,

        application: data.application
          ? {
              connect: data.application,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        application: {
          select: {
            id: true,
          },
        },

        certificateNumber: true,
        completionDate: true,
        createdAt: true,
        id: true,
        provider: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Training] })
  @ApiNestedQuery(TrainingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Training",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async trainings(@common.Req() request: Request): Promise<Training[]> {
    const args = plainToClass(TrainingFindManyArgs, request.query);
    return this.service.trainings({
      ...args,
      select: {
        application: {
          select: {
            id: true,
          },
        },

        certificateNumber: true,
        completionDate: true,
        createdAt: true,
        id: true,
        provider: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Training })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Training",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async training(
    @common.Param() params: TrainingWhereUniqueInput
  ): Promise<Training | null> {
    const result = await this.service.training({
      where: params,
      select: {
        application: {
          select: {
            id: true,
          },
        },

        certificateNumber: true,
        completionDate: true,
        createdAt: true,
        id: true,
        provider: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Training })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Training",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTraining(
    @common.Param() params: TrainingWhereUniqueInput,
    @common.Body() data: TrainingUpdateInput
  ): Promise<Training | null> {
    try {
      return await this.service.updateTraining({
        where: params,
        data: {
          ...data,

          application: data.application
            ? {
                connect: data.application,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          application: {
            select: {
              id: true,
            },
          },

          certificateNumber: true,
          completionDate: true,
          createdAt: true,
          id: true,
          provider: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Training })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Training",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTraining(
    @common.Param() params: TrainingWhereUniqueInput
  ): Promise<Training | null> {
    try {
      return await this.service.deleteTraining({
        where: params,
        select: {
          application: {
            select: {
              id: true,
            },
          },

          certificateNumber: true,
          completionDate: true,
          createdAt: true,
          id: true,
          provider: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
