/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { InstitutionService } from "../institution.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { InstitutionCreateInput } from "./InstitutionCreateInput";
import { Institution } from "./Institution";
import { InstitutionFindManyArgs } from "./InstitutionFindManyArgs";
import { InstitutionWhereUniqueInput } from "./InstitutionWhereUniqueInput";
import { InstitutionUpdateInput } from "./InstitutionUpdateInput";
import { ApplicationFindManyArgs } from "../../application/base/ApplicationFindManyArgs";
import { Application } from "../../application/base/Application";
import { ApplicationWhereUniqueInput } from "../../application/base/ApplicationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class InstitutionControllerBase {
  constructor(
    protected readonly service: InstitutionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Institution })
  @nestAccessControl.UseRoles({
    resource: "Institution",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createInstitution(
    @common.Body() data: InstitutionCreateInput
  ): Promise<Institution> {
    return await this.service.createInstitution({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        name: true,
        registrationNumber: true,
        typeField: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        verified: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Institution] })
  @ApiNestedQuery(InstitutionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Institution",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async institutions(@common.Req() request: Request): Promise<Institution[]> {
    const args = plainToClass(InstitutionFindManyArgs, request.query);
    return this.service.institutions({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        registrationNumber: true,
        typeField: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        verified: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Institution })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Institution",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async institution(
    @common.Param() params: InstitutionWhereUniqueInput
  ): Promise<Institution | null> {
    const result = await this.service.institution({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        registrationNumber: true,
        typeField: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        verified: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Institution })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Institution",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateInstitution(
    @common.Param() params: InstitutionWhereUniqueInput,
    @common.Body() data: InstitutionUpdateInput
  ): Promise<Institution | null> {
    try {
      return await this.service.updateInstitution({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          name: true,
          registrationNumber: true,
          typeField: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          verified: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Institution })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Institution",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteInstitution(
    @common.Param() params: InstitutionWhereUniqueInput
  ): Promise<Institution | null> {
    try {
      return await this.service.deleteInstitution({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          registrationNumber: true,
          typeField: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          verified: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/applications")
  @ApiNestedQuery(ApplicationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Application",
    action: "read",
    possession: "any",
  })
  async findApplications(
    @common.Req() request: Request,
    @common.Param() params: InstitutionWhereUniqueInput
  ): Promise<Application[]> {
    const query = plainToClass(ApplicationFindManyArgs, request.query);
    const results = await this.service.findApplications(params.id, {
      ...query,
      select: {
        applicationNumber: true,
        comments: true,
        createdAt: true,
        id: true,

        institution: {
          select: {
            id: true,
          },
        },

        status: true,
        submissionDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/applications")
  @nestAccessControl.UseRoles({
    resource: "Institution",
    action: "update",
    possession: "any",
  })
  async connectApplications(
    @common.Param() params: InstitutionWhereUniqueInput,
    @common.Body() body: ApplicationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      applications: {
        connect: body,
      },
    };
    await this.service.updateInstitution({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/applications")
  @nestAccessControl.UseRoles({
    resource: "Institution",
    action: "update",
    possession: "any",
  })
  async updateApplications(
    @common.Param() params: InstitutionWhereUniqueInput,
    @common.Body() body: ApplicationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      applications: {
        set: body,
      },
    };
    await this.service.updateInstitution({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/applications")
  @nestAccessControl.UseRoles({
    resource: "Institution",
    action: "update",
    possession: "any",
  })
  async disconnectApplications(
    @common.Param() params: InstitutionWhereUniqueInput,
    @common.Body() body: ApplicationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      applications: {
        disconnect: body,
      },
    };
    await this.service.updateInstitution({
      where: params,
      data,
      select: { id: true },
    });
  }
}
