/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WorkExperienceService } from "../workExperience.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WorkExperienceCreateInput } from "./WorkExperienceCreateInput";
import { WorkExperience } from "./WorkExperience";
import { WorkExperienceFindManyArgs } from "./WorkExperienceFindManyArgs";
import { WorkExperienceWhereUniqueInput } from "./WorkExperienceWhereUniqueInput";
import { WorkExperienceUpdateInput } from "./WorkExperienceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WorkExperienceControllerBase {
  constructor(
    protected readonly service: WorkExperienceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WorkExperience })
  @nestAccessControl.UseRoles({
    resource: "WorkExperience",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWorkExperience(
    @common.Body() data: WorkExperienceCreateInput
  ): Promise<WorkExperience> {
    return await this.service.createWorkExperience({
      data: {
        ...data,

        application: data.application
          ? {
              connect: data.application,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        application: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        employerName: true,
        endDate: true,
        id: true,
        position: true,
        startDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WorkExperience] })
  @ApiNestedQuery(WorkExperienceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WorkExperience",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async workExperiences(
    @common.Req() request: Request
  ): Promise<WorkExperience[]> {
    const args = plainToClass(WorkExperienceFindManyArgs, request.query);
    return this.service.workExperiences({
      ...args,
      select: {
        application: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        employerName: true,
        endDate: true,
        id: true,
        position: true,
        startDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WorkExperience })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WorkExperience",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async workExperience(
    @common.Param() params: WorkExperienceWhereUniqueInput
  ): Promise<WorkExperience | null> {
    const result = await this.service.workExperience({
      where: params,
      select: {
        application: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        employerName: true,
        endDate: true,
        id: true,
        position: true,
        startDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WorkExperience })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WorkExperience",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWorkExperience(
    @common.Param() params: WorkExperienceWhereUniqueInput,
    @common.Body() data: WorkExperienceUpdateInput
  ): Promise<WorkExperience | null> {
    try {
      return await this.service.updateWorkExperience({
        where: params,
        data: {
          ...data,

          application: data.application
            ? {
                connect: data.application,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          application: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          employerName: true,
          endDate: true,
          id: true,
          position: true,
          startDate: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WorkExperience })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WorkExperience",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWorkExperience(
    @common.Param() params: WorkExperienceWhereUniqueInput
  ): Promise<WorkExperience | null> {
    try {
      return await this.service.deleteWorkExperience({
        where: params,
        select: {
          application: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          employerName: true,
          endDate: true,
          id: true,
          position: true,
          startDate: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
